[platformio]
src_dir = ESP32S3CAN-FSD

[env:lilygo_t2can_arduino_webui]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21/platform-espressif32.zip
board = esp32s3box
framework = arduino

board_build.flash_size = 16MB
board_build.flash_mode = dio
board_build.partitions = huge_app.csv
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi

lib_deps =
    autowp/autowp-mcp2515

build_flags =
    -DTWAI_TX_PIN=GPIO_NUM_7
    -DTWAI_RX_PIN=GPIO_NUM_6
    -DTWAI_RX_QUEUE_LEN=64
    -DTWAI_TX_QUEUE_LEN=16
    -DLILYGO_T2CAN
    -DENABLE_CANB_MCP2515
    -DMCP2515_SCK=12
    -DMCP2515_MOSI=11
    -DMCP2515_MISO=13
    -DMCP2515_CS=10
    -DMCP2515_RST=9
    -DMCP2515_INT=8
    -DMCP2515_CLOCK=MCP_16MHZ
    -DENABLE_LIGHT_WEBUI
    -DBOARD_HAS_PSRAM
    -DREC_CAP=100000
    -std=gnu++17

build_unflags =
    -std=gnu++11

upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200
